# Site settings
title: Inside the Klein bottle
tagline: Random thoughts neither here nor there
email: my@email.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome on this side of the bottle
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://alessiodimauro.com" # the base hostname & protocol for your site
logourl: /assets/images/klein42.png # Site logo
author: "Alessio Di Mauro"
author_thumbnail:    "/assets/images/avatar.jpg"   # Author avatar
sidebar_thumbnail:   "/assets/images/klein300.png" # Sidebar image
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#006699"

  # Social media links, leave blank to ignore
  social:
    github: a-dma
    twitter:
    facebook:
    gplus:
    linkedin: alessiodimauro
    pinterest:

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: false

  # Disqus comments manager - shortname
  disqus_shortname: alessiodimauro

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key:
  google_webmaster_key:

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - klein_bottle.gnu

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems:
  - jekyll-asciidoc
